spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Eco@2002
  jpa:
    show-sql: true
websiteUrl: http://localhost:4242